Update missing dependencies on Fedora based systems
fatal error: unistr.h: No such file or directory when trying to compile without libunistring-devel installed.